project:
  type: website

website:
  title: "OHID Sphere Optimisation Project Report"
  page-navigation: true
  navbar:
    logo: assets/logo/r-rse-logo2.png
    logo-href: https://www.r-rse.eu/
    pinned: true
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    center:
      - text: "r-rse | Research Software Engineering Services in R"
        href: https://www.r-rse.eu/
  sidebar:
    style: "docked"
    title: 'Contents'
    contents:
      - text: "SPHERE High Level Review"
        href: 01_SPHERE-review.qmd
      - text: "SPHERE Debugging Comments"
        href: 02_SPHERE-debugging.qmd

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    mainfont: 'Work Sans'
    monofont: 'Cutive Mono'

execute:
  freeze: auto

editor: visual

